# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
anthropic = "2.12.0"
clikt = "5.1.0"
commonsCompress = "1.28.0"
detekt = "2.0.0-alpha.1"
googleGenai = "1.37.0"
javaGi = "0.13.1"
kotlin = "2.3.0"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
ktor = "3.4.0"
log4j = "2.25.3"
openai = "4.17.0"
shadow = "9.3.1"

[libraries]
anthropic = { module = "com.anthropic:anthropic-java", version.ref = "anthropic" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
commonsCompress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
googleGenai = { module = "com.google.genai:google-genai", version.ref = "googleGenai" }
javaGiAdw = { module = "org.java-gi:adw", version.ref = "javaGi" }
javaGiGtk = { module = "org.java-gi:gtk", version.ref = "javaGi" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
log4jApi = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
openai = { module = "com.openai:openai-java", version.ref = "openai" }

[bundles]
javaGiEcosystem = ["javaGiGtk", "javaGiAdw"]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
ktorClient = ["ktorClientCore", "ktorClientContentNegotiation", "ktorSerializationKotlinxJson"]

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
