# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
anthropic = "2.12.0"
buildconfig = "6.0.7"
clikt = "5.1.0"
commonsCompress = "1.28.0"
detekt = "2.0.0-alpha.2"
googleGenai = "1.37.0"
javaGi = "0.14.0"
kotlin = "2.3.10"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.10.0"
kover = "0.9.7"
ktor = "3.4.0"
log4j = "2.25.3"
onnx = "1.24.1"
onnxExtensions = "0.13.0"
openai = "4.17.0"
shadow = "9.3.1"
stargate = "0.1.0"
versionsPlugin = "0.53.0"

[libraries]
anthropic = { module = "com.anthropic:anthropic-java", version.ref = "anthropic" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
commonsCompress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
googleGenai = { module = "com.google.genai:google-genai", version.ref = "googleGenai" }
javaGiAdw = { module = "org.java-gi:adw", version.ref = "javaGi" }
javaGiGtk = { module = "org.java-gi:gtk", version.ref = "javaGi" }
javaGiGstreamer = { module = "org.java-gi:gstreamer", version.ref = "javaGi" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
log4jCore = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4jSlf4j2Impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
onnxRuntime = { module = "com.microsoft.onnxruntime:onnxruntime", version.ref = "onnx" }
onnxRuntimeGpu = { module = "com.microsoft.onnxruntime:onnxruntime_gpu", version.ref = "onnx" }
onnxRuntimeExtensions = { module = "com.microsoft.onnxruntime:onnxruntime-extensions", version.ref = "onnxExtensions" }
openai = { module = "com.openai:openai-java", version.ref = "openai" }
stargate = { module = "com.github.zugaldia:stargate", version.ref = "stargate" }

[bundles]
javaGiEcosystem = ["javaGiGtk", "javaGiAdw", "javaGiGstreamer"]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
ktorEcosystem = ["ktorClientCore", "ktorClientCio"]
onnxEcosystem = ["onnxRuntime", "onnxRuntimeExtensions"]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
